apiVersion: v1
kind: ConfigMap
metadata:
  name: msa-k8s-configmap
data:
  gateway_ip: "192.168.49.2"
  token_expiration_time: "8640000"
  token_secret: "myverylongandlongalsolongsecretkey1234567890123456123456"
  order-service-url: "http://order-service:10000"
  bootstrap-service: "192.168.49.2:9092"
  mysql_user_service_username: user_svc
  mysql_user_service_password: user_pw!
  mysql_user_service_url: jdbc:mysql://localhost:3306/msalearn
  mysql_order_service_username: order_svc
  mysql_order_service_password: order_pw!
  mysql_order_service_url: jdbc:mysql://localhost:3306/msalearn_order
  mysql_catalog_service_username: catalog_svc
  mysql_catalog_service_password: catalog_pw!
  mysql_catalog_service_url: jdbc:mysql://localhost:3306/msalearn_catalog