apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deploy
spec:
  selector:
    matchLabels:
      app: order-app
  replicas: 1
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
        - name: order-service
          image: dkdkko/order-service:k8s_v1.6_temp
          imagePullPolicy: Always
          ports:
            - containerPort: 10000
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
          env:
            - name: BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: bootstrap-servers
            - name: MYSQL_ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: mysql_order_service_url
            - name: MYSQL_ORDER_SERVICE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: mysql_order_service_username
            - name: MYSQL_ORDER_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: mysql_order_service_password
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: NodePort
  selector:
    app: order-app
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000
      nodePort: 30002