server:
  port: 60000

spring:
  datasource:
    url: ${MYSQL_USER_SERVICE_URL}
    username: ${MYSQL_USER_SERVICE_USERNAME}
    password: ${MYSQL_USER_SERVICE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      defer-datasource-initialization: true

greeting:
  message: Welcome to the Simple E-commerce - 2nd.

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

token:
  expiration-time: ${TOKEN_EXPIRATION_TIME}
  secret: ${TOKEN_SECRET}

order-service-url: ${ORDER-SERVICE-URL}

gateway:
  ip: ${GATEWAY_IP}